settings:
  # The channel all new ticket creation will be sent to
  ticket_log_channel: ""
  # The channel where the application message (active/not active) will be sent to
  application_message_channel: ""

# The types of roles that can be applied for. Duplicate one of the roles that already exist
# to create a new one, you can add as many as you like
application_types: [
  {
    # The name of the role
    name: "Supporter",
    # The role description, meaning their supposed work in the team
    description: "Helps users ingame and handles reports",
    # The roles emoji, that will be shown in the list of applicable roles
    emoji: "",
    #  The roles id, meaning the discord role itself
    role_id: ""
  },
  {
    # The name of the role
    name: "Discord Supporter",
    # The role description, meaning their supposed work in the team
    description: "Helps users on the discord handling discord tickets",
    # The roles emoji, that will be shown in the list of applicable roles
    emoji: "",
    #  The roles id, meaning the discord role itself
    role_id: ""
  },
  {
    # The name of the role
    name: "Developer",
    # The role description, meaning their supposed work in the team
    description: "Develops plugins or helps with server maintenance",
    # The roles emoji, that will be shown in the list of applicable roles
    emoji: "",
    #  The roles id, meaning the discord role itself
    role_id: ""
  }
]

# ** WARNING ** Do not add or remove any types as it will cause errors
# The types of tickets that can be opened
types: [
  {
    # The name of the ticket type
    name: "General",
    # ** WARNING ** Do not change this as it will change how the bot defines
    # the type defines the ticket in the code
    type: "support::GENERAL",
    # The roles that will be added to the ticket once it is created
    roles: [ ],
    # The roles that can interact with the tickets log
    log_permissions_roles: [ ],
    # The channel that the ticket will be created under (ticket is a thread)
    parent_channel: "",
    child_rules: {
      # ** WARNING ** Do not remove the %r% in the type name as it will cause errors
      # The naming scheme the ticket type follows, the %r% stands for the number of the ticket
      parent_name: "Ticket #%r%",
      # ** WIP ** This feature has not been implemented yet, and it's implication is not certain for 100%
      # Should the status bar be displayed
      use_status_bar: true,
      # ** WIP ** This feature has not been implemented yet
      # Should the ticket be locked when first created, needing a staff member to unlock it
      lock_on_default: false
    }
  },
  {
    # The name of the ticket type
    name: "Report",
    # ** WARNING ** Do not change this as it will change how the bot defines
    # the type defines the ticket in the code
    type: "support::REPORT",
    # The roles that will be added to the ticket once it is created
    roles: [ ],
    # The roles that can interact with the tickets log
    log_permissions_roles: [ ],
    # The channel that the ticket will be created under (ticket is a thread)
    parent_channel: "",
    child_rules: {
      # ** WARNING ** Do not remove the %r% in the type name as it will cause errors
      # The naming scheme the ticket type follows, the %r% stands for the number of the ticket
      parent_name: "Ticket #%r%",
      # ** WIP ** This feature has not been implemented yet, and it's implication is not certain for 100%
      # Should the status bar be displayed
      use_status_bar: true,
      # ** WIP ** This feature has not been implemented yet
      # Should the ticket be locked when first created, needing a staff member to unlock it
      lock_on_default: false
    }
  },
  {
    # The name of the ticket type
    name: "Error",
    # ** WARNING ** Do not change this as it will change how the bot defines
    # the type defines the ticket in the code
    type: "support::ERROR",
    # The roles that will be added to the ticket once it is created
    roles: [ ],
    # The roles that can interact with the tickets log
    log_permissions_roles: [ ],
    # The channel that the ticket will be created under (ticket is a thread)
    parent_channel: "",
    child_rules: {
      # ** WARNING ** Do not remove the %r% in the type name as it will cause errors
      # The naming scheme the ticket type follows, the %r% stands for the number of the ticket
      parent_name: "Ticket #%r%",
      # ** WIP ** This feature has not been implemented yet, and it's implication is not certain for 100%
      # Should the status bar be displayed
      use_status_bar: true,
      # ** WIP ** This feature has not been implemented yet
      # Should the ticket be locked when first created, needing a staff member to unlock it
      lock_on_default: false
    }
  },
  {
    # The name of the ticket type
    name: "Unban",
    # ** WARNING ** Do not change this as it will change how the bot defines
    # the type defines the ticket in the code
    type: "support::UNBAN",
    # The roles that will be added to the ticket once it is created
    roles: [ ],
    # The roles that can interact with the tickets log
    log_permissions_roles: [ ],
    # The channel that the ticket will be created under (ticket is a thread)
    parent_channel: "",
    child_rules: {
      # ** WARNING ** Do not remove the %r% in the type name as it will cause errors
      # The naming scheme the ticket type follows, the %r% stands for the number of the ticket
      parent_name: "Ticket #%r%",
      # ** WIP ** This feature has not been implemented yet, and it's implication is not certain for 100%
      # Should the status bar be displayed
      use_status_bar: true,
      # ** WIP ** This feature has not been implemented yet
      # Should the ticket be locked when first created, needing a staff member to unlock it
      lock_on_default: false
    }
  },
  {
    # The name of the ticket type
    name: "Complaint",
    # ** WARNING ** Do not change this as it will change how the bot defines
    # the type defines the ticket in the code
    type: "support::COMPLAINT",
    # The roles that will be added to the ticket once it is created
    roles: [ ],
    # The roles that can interact with the tickets log
    log_permissions_roles: [ ],
    # The channel that the ticket will be created under (ticket is a thread)
    parent_channel: "",
    child_rules: {
      # ** WARNING ** Do not remove the %r% in the type name as it will cause errors
      # The naming scheme the ticket type follows, the %r% stands for the number of the ticket
      parent_name: "Ticket #%r%",
      # ** WIP ** This feature has not been implemented yet, and it's implication is not certain for 100%
      # Should the status bar be displayed
      use_status_bar: true,
      # ** WIP ** This feature has not been implemented yet
      # Should the ticket be locked when first created, needing a staff member to unlock it
      lock_on_default: false
    }
  },
  {
    # The name of the ticket type
    name: "Application",
    # ** WARNING ** Do not change this as it will change how the bot defines
    # the type defines the ticket in the code
    type: "support::APPLICATION",
    # The roles that will be added to the ticket once it is created
    roles: [ ],
    # The roles that can interact with the tickets log
    log_permissions_roles: [ ],
    # The channel that the ticket will be created under (ticket is a thread)
    parent_channel: "",
    child_rules: {
      # ** WARNING ** Do not remove the %r% in the type name as it will cause errors
      # The naming scheme the ticket type follows, the %r% stands for the number of the ticket
      parent_name: "Ticket #%r%",
      # ** WIP ** This feature has not been implemented yet, and it's implication is not certain for 100%
      # Should the status bar be displayed
      use_status_bar: true,
      # ** WIP ** This feature has not been implemented yet
      # Should the ticket be locked when first created, needing a staff member to unlock it
      lock_on_default: false
    }
  },
]