#                                                            ______     ______     ______     __  __     __         ______     ______     ______
#                                                           /\  == \   /\  ___\   /\  ___\   /\ \/\ \   /\ \       /\  __ \   /\  == \   /\  ___\
#                                                           \ \  __<   \ \  __\   \ \ \__ \  \ \ \_\ \  \ \ \____  \ \  __ \  \ \  __<   \ \___  \
#                                                            \ \_\ \_\  \ \_____\  \ \_____\  \ \_____\  \ \_____\  \ \_\ \_\  \ \_\ \_\  \/\_____\
#                                                            \/_/ /_/   \/_____/   \/_____/   \/_____/   \/_____/   \/_/\/_/   \/_/ /_/   \/_____/



# The list of roles that will be available for users. To create more copy an already existing entry.
# To remove a regular, delete an entry.
roles: [
  {
    # The roleId of the role. Activate developer mode and right-click the role
    id: "",
    # The description of the role that will be displayed to the user
    description: "",
    # Which type of requirement do you want to use? The requirement_type will define if the role is given to the player when reaching a certain
    # playtime, a certain level, or both. Choose between the types: [PLAYTIME, XP, BOTH]
    requirement_type: "PLAYTIME",
    # Which playtime (in hours) does the user need to reach before getting the role?
    playtime_requirement: 25,
    # Which xp level (in end levels) should the user need to reach before getting the role?
    xp_requirement: 5
  },
  {
    # The roleId of the role. Activate developer mode and right-click the role
    id: "",
    # The description of the role that will be displayed to the user
    description: "",
    # Which type of requirement do you want to use? The requirement_type will define if the role is given to the player when reaching a certain
    # playtime, a certain level, or both. Choose between the types: [PLAYTIME, XP, BOTH]
    requirement_type: "PLAYTIME",
    # Which playtime (in hours) does the user need to reach before getting the role?
    playtime_requirement: 50,
    # Which xp level (in end levels) should the user need to reach before getting the role?
    xp_requirement: 10
  },
  {
    # The roleId of the role. Activate developer mode and right-click the role
    id: "",
    # The description of the role that will be displayed to the user
    description: "",
    # Which type of requirement do you want to use? The requirement_type will define if the role is given to the player when reaching a certain
    # playtime, a certain level, or both. Choose between the types: [PLAYTIME, XP, BOTH]
    requirement_type: "PLAYTIME",
    # Which playtime (in hours) does the user need to reach before getting the role?
    playtime_requirement: 100,
    # Which xp level (in end levels) should the user need to reach before getting the role?
    xp_requirement: 15
  },
  {
    # The roleId of the role. Activate developer mode and right-click the role
    id: "",
    # The description of the role that will be displayed to the user
    description: "",
    # Which type of requirement do you want to use? The requirement_type will define if the role is given to the player when reaching a certain
    # playtime, a certain level, or both. Choose between the types: [PLAYTIME, XP, BOTH]
    requirement_type: "PLAYTIME",
    # Which playtime (in hours) does the user need to reach before getting the role?
    playtime_requirement: 150,
    # Which xp level (in end levels) should the user need to reach before getting the role?
    xp_requirement: 20
  },
]