# Your options for translating are the following colors:
# [DARK_GRAY, RED, GREEN, GOLD, LiGHT_BLUE, PINK, TEAL, WHITE]
# Hashvalues must be surrounded by <>, example: <#FFFFFF>
Scp_Colors_List: [
    {PINK: "test"},
    {RED: "RED"},
    {BROWN: "WHITE"},
    {SILVER: "DARK_GRAY"},
    {LIGHT_GREEN: "GREEN"},
    {CRIMSON: "RED"},
    {CYAN: "TEAL"},
    {AQUA: "TEAL"},
    {DEEP_PINK: "RED"},
    {TOMATO: "RED"},
    {YELLOW: "GOLD"},
    {MAGENTA: "RED"},
    {BLUE_GREEN: "GREEN"},
    {ORANGE: "RED"},
    {LIME: "GREEN"},
    {GREEN: "GREEN"},
    {EMERALD: "GREEN"},
    {CARMINE: "RED"},
    {NICKEL: "DARK_GRAY"},
    {MINT: "GREEN"},
    {ARMY_GREEN: "GREEN"},
    {PUMPKIN: "RED"},
]