# The bot token get from here https://discord.com/developers/
token: ""
# The guild id. Get using developer mode in discord and then right-clicking on the server, then copy id
# \__ go to Settings > Advanced > Developer Mode
guild_id: ""

# The activity type of the bot [COMPETING, CUSTOM_STATUS, LISTENING, PLAYING, WATCHING]
activity_type: "PLAYING"
# The text being displayed
activity_content: "/help"

# Rules Settings
rules:
  pastebin: ""
  embed_footer: "Official Server Ruleset"

# Commands that are activated by default remove to deactivate, default ["help", "template"]]
commands: ["help", "template"]
# Command settings
# 'default_permissions' is pretty clear, find all permissions in this Javadoc https://docs.jda.wiki/net/dv8tion/jda/api/Permission.html.
command_settings:
  help:
    default_permissions: ["ADMINISTRATOR"]
    description: "Command annotations and explanations"
  template:
    default_permissions: ["ADMINISTRATOR"]
    description: "Command for pasting certain templates"

support_settings:
  # Enter ROLEIDS of roles to automatically add to new tickets
  roles_access_support_tickets: []
  # Enter ROLEIDS of roles that should be able to interact with unbanning requests
  roles_access_unban_tickets: []
  # Which channel should unban requests be sent to
  unban_channel_id: ""

notice_of_departure:
  # Which channel should the form be sent to be accepted by moderators?
  decision_channel_id: ""
  # Which channel should the departures be sent to?
  notice_channel_id: ""
  # List of role's that are able to accept/dismiss/revoke notices (INPUT ID'S ONLY)
  roles_access_notices: []
  # ONLY CHANGE THIS IF YOU KNOW WHAT YOU'RE DOING
  check_on_startup: true
  # Put the following in the type: [NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS]
  check_type: "HOURS"
  # The rate at that the notices are checked.
  check_rate: 1

cedmod:
  # Should Cedmod integration features be established or deactivated?
  active: false
  # Include https://
  instance_url: ""
  # Exclude Bearer, put plain api key
  api_key: ""
  # This bot is only able to unban people that are on this banlist (feature for multi banlist bans coming in the future)
  master_ban_list_id: ""