# The bot token get from here https://discord.com/developers/
token: ""
# The guild id. Get using developer mode in discord and then right-clicking on the server, then copy id
# \__ go to Settings > Advanced > Developer Mode
guild_id: ""

# The activity type of the bot [COMPETING, CUSTOM_STATUS, LISTENING, PLAYING, WATCHING]
activity_type: "PLAYING"
# The text being displayed
activity_content: "/help"

# Rules Settings
rules:
  pastebin: ""
  embed_footer: "Official Server Ruleset"

# Commands that are activated by default remove to deactivate, default ["help"]
commands: ["help", "template"]
# Command settings
# 'default_permissions' is pretty clear, find all permissions in this Javadoc https://docs.jda.wiki/net/dv8tion/jda/api/Permission.html.
command_settings:
  help:
    default_permissions: ["ADMINISTRATOR"]
    description: "Command annotations and explanations"
  template:
    default_permissions: ["ADMINISTRATOR"]
    description: "Command for pasting certain templates"

support_settings:
  roles_access_tickets: []